In [1]:
import numpy as np

In [2]:
# Reading elements from an array

In [3]:
a =np.arange(10, 20)

In [4]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [5]:
a[0]

10

In [6]:
a[1:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [7]:
a[1:4]

array([11, 12, 13])

In [8]:
b = [[1,2],[3,4]]

In [9]:
c= np.array(b)

In [10]:
b

[[1, 2], [3, 4]]

In [11]:
c

array([[1, 2],
       [3, 4]])

In [13]:
b[1][0]

3

In [14]:
c[1, 0]

3

In [16]:
a[-3:-1]

array([17, 18])

In [21]:
ar = np.arange(10, 30)

In [22]:
ar

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [23]:
np.where(ar % 2 == 0)

(array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18], dtype=int64),)

In [25]:
np.where(ar % 2 == 0, 0, ar)

array([ 0, 11,  0, 13,  0, 15,  0, 17,  0, 19,  0, 21,  0, 23,  0, 25,  0,
       27,  0, 29])

In [26]:
p2 = np.arange(0, 100, 10)

In [28]:
p2

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [33]:
aa = np.put(p2, [0, 3, 5], [33, 55, 99])

In [30]:
p2

array([33, 10, 20, 55, 40, 99, 60, 70, 80, 90])

In [31]:
np.insert(p2, 1, 0)

array([33,  0, 10, 20, 55, 40, 99, 60, 70, 80, 90])

In [32]:
p2

array([33, 10, 20, 55, 40, 99, 60, 70, 80, 90])

In [35]:
aa is None

True

In [36]:
# Not a Number
np.nan

nan

In [37]:
# Infinity
np.inf

inf

In [38]:
1000000 < np.inf

True

In [39]:
np.inf == np.inf

True

In [40]:
np.nan == np.nan

False

In [41]:
np.isnan(np.nan)

True

In [42]:
np.isnan(np.inf)

False

In [44]:
a = np.array([10, np.nan, 20, 30, 60, np.nan, 90, np.inf])
a

array([10., nan, 20., 30., 60., nan, 90., inf])

In [45]:
np.isnan(a)

array([False,  True, False, False, False,  True, False, False])

In [46]:
np.where(np.isnan(a))

(array([1, 5], dtype=int64),)

In [47]:
a[np.isnan(a)] = 0

In [48]:
a

array([10.,  0., 20., 30., 60.,  0., 90., inf])

In [49]:
a = np.array([10, np.nan, 20, 30, 60, np.nan, 90, np.inf])
a

array([10., nan, 20., 30., 60., nan, 90., inf])

In [53]:
np.isnan(a).any()

True

In [54]:
np.isnan(a).all()

False

In [55]:
A=np.array([[1,2,np.nan,4],[np.nan,6,7,8]])

In [56]:
A

array([[ 1.,  2., nan,  4.],
       [nan,  6.,  7.,  8.]])

In [60]:
# Indexing
A[0][2]
A[0, 2]

nan

In [61]:
np.isnan(A)

array([[False, False,  True, False],
       [ True, False, False, False]])

In [64]:
a = np.array([1, 2, 3, 6, 8])
b = np.array([10,2,30,60, 8])

In [65]:
np.where(a == b)

(array([1, 4], dtype=int64),)

In [67]:
a = np.arange(0, 60)
a[np.where((a>20) & (a<35))]

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

In [68]:
a[np.where(np.logical_not(a>20))]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [69]:
a[np.where(np.logical_and(a>20, a<35))]

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

In [70]:
a[np.where(~(a>20) & (a<35))]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [71]:
# np.logical_not -> ~

In [77]:
b = np.where(((a > 20) & (a < 35)) | a % 10 == 0)

In [78]:
b

(array([ 0, 10, 20, 40, 50], dtype=int64),)

In [79]:
b = np.where(((a > 20) & (a < 35)) | (a % 5 == 0))

In [80]:
b

(array([ 0,  5, 10, 15, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
        33, 34, 35, 40, 45, 50, 55], dtype=int64),)

In [82]:
a = np.arange(0, 101)

In [86]:
b = np.array([11, 20, 40, 102])

In [88]:
np.isin(b, a)

array([ True,  True,  True, False])

In [89]:
b[np.isin(b, a)]

array([11, 20, 40])

In [90]:
np.where(np.isin(b, a))

(array([0, 1, 2], dtype=int64),)

In [91]:
# Reverse Array

In [94]:
a = np.arange(10, 30)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [95]:
a[::-1]

array([29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13,
       12, 11, 10])

In [96]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [98]:
np.flip(a)

array([29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13,
       12, 11, 10])

In [99]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [100]:
a = np.flip(a)

In [101]:
a

array([29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13,
       12, 11, 10])

In [102]:
a = np.arange(9).reshape(3, 3)

In [103]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [105]:
b = np.arange(12).reshape(3, 4)

In [106]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [107]:
b = np.arange(12).reshape(3, -1)

In [108]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [109]:
c = np.arange(12).reshape(5, -1)

ValueError: cannot reshape array of size 12 into shape (5,newaxis)

In [110]:
c = np.arange(12).reshape(-1, 4)

In [111]:
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [112]:
c[0]

array([0, 1, 2, 3])

In [113]:
c[:, 1]

array([1, 5, 9])

In [114]:
c[0, :]

array([0, 1, 2, 3])

In [116]:
c[1,1::2]

array([5, 7])

In [118]:
# Reverse ROW position
c[::-1,]

array([[ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])

In [119]:
# Reverse COLUMN position
c[:, ::-1]

array([[ 3,  2,  1,  0],
       [ 7,  6,  5,  4],
       [11, 10,  9,  8]])

In [120]:
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [121]:
a = np.arange(0, 20)

In [122]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [123]:
np.random.shuffle(a)

In [124]:
a

array([16,  9,  0,  5, 12, 14, 18, 13,  8,  4, 11,  1,  2, 19,  3,  6, 15,
       17, 10,  7])

In [125]:
np.random.permutation(a)

array([15, 16,  6, 14, 12,  0, 13,  5,  8,  2,  7, 17,  4, 18,  1, 10,  3,
       11,  9, 19])

In [126]:
# SORT
np.sort(a)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [130]:
np.random.shuffle(c)

In [131]:
c

array([[ 4,  5,  6,  7],
       [ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [139]:
c = c.flatten()
np.random.shuffle(c)
c = c.reshape(3, -1)

In [140]:
c

array([[ 6,  3, 10, 11],
       [ 8,  2,  4,  7],
       [ 5,  0,  9,  1]])

In [141]:
np.sort(c)

array([[ 3,  6, 10, 11],
       [ 2,  4,  7,  8],
       [ 0,  1,  5,  9]])

In [144]:
np.sort(c, axis=None)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [145]:
np.random.seed(101)
a = np.random.randint(1, 101, 20)

In [146]:
a

array([96, 12, 82, 71, 64, 88, 76, 10, 78, 41,  5, 64, 41, 61, 93, 65,  6,
       13, 94, 41])

In [154]:
np.sort(a)

array([ 5,  6, 10, 12, 13, 41, 41, 41, 61, 64, 64, 65, 71, 76, 78, 82, 88,
       93, 94, 96])

In [152]:
n = 5
np.sort(a)[-n:]

array([82, 88, 93, 94, 96])

In [153]:
np.argsort(a)

array([10, 16,  7,  1, 17,  9, 12, 19, 13, 11,  4, 15,  3,  6,  8,  2,  5,
       14, 18,  0], dtype=int64)

In [155]:
a[np.argsort(a)[-n:]]

array([82, 88, 93, 94, 96])

In [159]:
# Frequent Values in an array
a = np.array([10,10,10,20,30,20,30,30,20,10,10,30,10, 40])

In [160]:
np.unique(a)

array([10, 20, 30, 40])

In [162]:
np.unique(a, return_counts=True)

(array([10, 20, 30, 40]), array([6, 3, 4, 1], dtype=int64))

In [163]:
l1 = [1, 2]
l2 = [3, 4]

In [164]:
l1 + l2

[1, 2, 3, 4]

In [165]:
# Vector Addition
v1 = np.array(l1)
v2 = np.array(l2)
v3 = v1 + v2

In [166]:
v3

array([4, 6])

In [167]:
l1 + 2

TypeError: can only concatenate list (not "int") to list

In [168]:
v1 + 2

array([3, 4])

In [169]:
l1 * 2

[1, 2, 1, 2]

In [170]:
v1 * 2

array([2, 4])

In [171]:
l1 / 2

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [172]:
v1 / 2

array([0.5, 1. ])

In [173]:
l1 = [5, 6, 8]
l2 = [4, 7, 9]
v1 = np.array(l1)
v2 = np.array(l2)

In [174]:
np.multiply(v1, v2)

array([20, 42, 72])

In [175]:
v1 * v2

array([20, 42, 72])

In [177]:
v1 @ v2

134

In [178]:
sum(v1 * v2)

134

In [179]:
m1 = np.arange(1, 21).reshape(4, 5)
m2 = np.arange(10).reshape(5, -1)

In [180]:
m1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [181]:
m2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [182]:
m1 * m2

ValueError: operands could not be broadcast together with shapes (4,5) (5,2) 

In [183]:
m1 @ m2

array([[ 80,  95],
       [180, 220],
       [280, 345],
       [380, 470]])

In [184]:
# (4 * 5) * (5 * 2) -> 4, 2

In [186]:
v1

array([5, 6, 8])

In [187]:
np.sqrt(v1)

array([2.23606798, 2.44948974, 2.82842712])

In [188]:
import math

In [189]:
math.sqrt(v1)

TypeError: only size-1 arrays can be converted to Python scalars

In [190]:
np.eye(9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [191]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [192]:
np.diag([1,2,3,4],2)

array([[0, 0, 1, 0, 0, 0],
       [0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 3, 0],
       [0, 0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [193]:
np.sin(0)

0.0

In [194]:
np.cos(0)

1.0

In [195]:
np.arcsin(0)

0.0

In [197]:
np.arccos(1)

0.0

In [198]:
np.e

2.718281828459045

In [199]:
np.log(np.e)

1.0

In [205]:
a = []
a += [0]
a += [1]
for i in range(2, 200):
    a += [a[i - 1] + a[i - 2]]

In [206]:
a = np.array(a)

In [207]:
a[-1] / a[-2]

1.618033988749895

In [208]:
np.log10(100)

2.0

In [209]:
np.log2(4)

2.0

In [211]:
a = np.array([[4, 2], [8, 10]])
b = np.array([8, 28])

In [212]:
np.linalg.solve(a, b)

array([1., 2.])

In [215]:
t1 = np.array([
    [[1,2,3],[4,5,6],[7,8,9]],
    [[10,11,12],[13,14,15],[16,17,18]],
    [[100,200,300],[400,500,600],[700,800,900]]
])

In [216]:
t1

array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[ 10,  11,  12],
        [ 13,  14,  15],
        [ 16,  17,  18]],

       [[100, 200, 300],
        [400, 500, 600],
        [700, 800, 900]]])

In [219]:
t1[:,:,1]

array([[  2,   5,   8],
       [ 11,  14,  17],
       [200, 500, 800]])

In [221]:
t2 = np.arange(27)
np.random.shuffle(t2)
t2 = t2.reshape(3,3,3)

In [223]:
t2.shape

(3, 3, 3)

In [224]:
t1.shape

(3, 3, 3)

In [225]:
t1 + t2

array([[[  2,  28,  23],
        [ 20,  10,   9],
        [ 11,  14,  27]],

       [[ 24,  24,  21],
        [ 13,  21,  26],
        [ 40,  38,  28]],

       [[123, 212, 302],
        [422, 525, 608],
        [715, 819, 917]]])

In [226]:
np.add(t1, t2)

array([[[  2,  28,  23],
        [ 20,  10,   9],
        [ 11,  14,  27]],

       [[ 24,  24,  21],
        [ 13,  21,  26],
        [ 40,  38,  28]],

       [[123, 212, 302],
        [422, 525, 608],
        [715, 819, 917]]])

In [227]:
t1 - t2

array([[[  0, -24, -17],
        [-12,   0,   3],
        [  3,   2,  -9]],

       [[ -4,  -2,   3],
        [ 13,   7,   4],
        [ -8,  -4,   8]],

       [[ 77, 188, 298],
        [378, 475, 592],
        [685, 781, 883]]])

In [228]:
np.subtract(t1, t2)

array([[[  0, -24, -17],
        [-12,   0,   3],
        [  3,   2,  -9]],

       [[ -4,  -2,   3],
        [ 13,   7,   4],
        [ -8,  -4,   8]],

       [[ 77, 188, 298],
        [378, 475, 592],
        [685, 781, 883]]])

In [229]:
t1 * t2

array([[[    1,    52,    60],
        [   64,    25,    18],
        [   28,    48,   162]],

       [[  140,   143,   108],
        [    0,    98,   165],
        [  384,   357,   180]],

       [[ 2300,  2400,   600],
        [ 8800, 12500,  4800],
        [10500, 15200, 15300]]])

In [230]:
# np.multiply()
# np.divide()

In [231]:
np.tensordot(t1, t2)

array([[  717,   722,   462],
       [ 1788,  1928,  1344],
       [71700, 72200, 46200]])

In [237]:
import random
import math

In [239]:
def manhathan_distance(x, y):
    return abs(x) + abs(y)

In [235]:
def random_walk(steps):
    current_x = 0
    current_y = 0
    for _ in range(steps):
        direction = random.randint(0, 3)
        # up
        if direction == 0:
            current_y += 1
        # down
        elif direction == 1:
            current_y -= 1
        # right
        elif direction == 2:
            current_x += 1
        # left
        else:
            current_x -= 1
    return current_x, current_y

In [236]:
random_walk(20)

(-1, -1)

In [241]:
manhathan_distance(-1, -1)

2

In [248]:
def random_walk2(steps):
    current_x, current_y = 0, 0
    for _ in range(steps):
        dx, dy = random.choice([(0, 1), (0, -1), (1, 0), (-1, 0)])
        current_x += dx
        current_y += dy
    return current_x, current_y

In [247]:
random_walk2(20)

(0, -2)

In [250]:
# What is the longest random walk you can take so that on average you will end up 4 blocks or fewer from home...