In [2]:
# # Animation

# import sys
# import random

# adr = r"C:\Users\Salar Shahryari\Pycharm Projects\Python Course 2\stdlib"
# sys.path.append(adr)

# from stdlib import stddraw, color

# radius = 0.02

# x = random.random()
# y = random.random()
# stddraw.setPenColor(color.ORANGE)
# # stddraw.point(x, y)

# vx = (random.random() - .5) / 10.0
# vy = (random.random() - .5) / 10.0

# while True:
#     stddraw.clear()
#     x += vx
#     y += vy
#     if x >= 1 - radius or x <= 0 + radius:
#         vx = -vx
#     if y >= 1 - radius or y <= 0 + radius:
#         vy = -vy
#     stddraw.filledCircle(x, y, radius)
#     # stddraw.point(x, y)
#     stddraw.show(30)

In [6]:
# Quiz1:

In [7]:
phrase = "how long are the words in this phrase"
def my_len(s):
     return list(map(len, phrase.split()))

my_len(phrase)

[3, 4, 3, 3, 5, 2, 4, 6]

In [8]:
# Quiz2:
from functools import reduce
# [1,2,3,4] -> 1234
def digits_to_num(digits):
    return reduce(lambda x, y: x*10 + y, digits)
print(digits_to_num([1,2,3,4]))
print(digits_to_num([4, 3, 2]))

1234
432


In [12]:
#Quiz3:
def filter_words(word_list, letter):
    return list(filter(lambda word: word[0] == letter, word_list))

words = ['hello', 'are', 'cat', 'dog', 'home', 'go', 'to', 'hi', 'house']
filter_words(word_list=words, letter='h')

['hello', 'home', 'hi', 'house']

In [21]:
#Quiz4:
def concatenate(L1, L2, connector):
    return [word1+connector+word2 for (word1, word2) in zip(L1, L2)]
l1 = ['A', 'B']
l2 = ['a', 'b']
concatenate(['A', 'B'], ['a', 'b'], '-')

['A-a', 'B-b']

In [23]:
#Quiz5:
def d_list(l):
    return {v: k for k, v in enumerate(l)}

lst = ['a', 'b', 'c']
d_list(lst)

{'a': 0, 'b': 1, 'c': 2}

In [26]:
#Quiz6:
def count_match_index(l):
    return len([v for i, v in enumerate(l) if i == v])
count_match_index([0,2,2,1,5,5,6,10])

4

# Generators

In [35]:
# def f():
#     return

# def g():
#     yield

In [34]:
def create_cube(n):
    result = []
    for x in range(n):
        result.append(x ** 3)
    return result

In [36]:
create_cube(10)

[0, 1, 8, 27, 64, 125, 216, 343, 512, 729]

In [37]:
def create_cube(n):
    for x in range(n):
        yield x ** 3

In [38]:
create_cube(10)

<generator object create_cube at 0x0000023662894748>

In [39]:
for x in create_cube(10):
    print(x)

0
1
8
27
64
125
216
343
512
729


In [40]:
list(create_cube(10))

[0, 1, 8, 27, 64, 125, 216, 343, 512, 729]

In [47]:
def fib(n):
    a = 0
    b = 1
    output = []
    for i in range(n):
        output.append(a)
        a, b = b, a + b
    return output

In [49]:
fib(10)

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34]

In [50]:
def gen_fib(n):
    a = 0
    b = 1
    for i in range(n):
        yield a
        a, b = b, a + b

In [51]:
gen_fib(10)

<generator object gen_fib at 0x0000023662894C48>

In [52]:
list(gen_fib(10))

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34]

In [71]:
class Animal:
    def __init__(self):
        self.struct = [1,2,3,4,5]
        
    def __iter__(self):
        for item in self.struct:
            yield item

In [76]:
def simple_gen():
    for x in range(4):
        yield x

In [77]:
a = simple_gen()

In [78]:
a

<generator object simple_gen at 0x0000023662894CC8>

In [83]:
next(a)

StopIteration: 

In [84]:
for x in simple_gen():
    print(x)

0
1
2
3


In [85]:
s = 'hello'

In [86]:
for letter in s:
    print(letter)

h
e
l
l
o


In [87]:
next(s)

TypeError: 'str' object is not an iterator

In [88]:
s = iter(s)

In [89]:
next(s)

'h'

In [92]:
def gen_squares(n):
    for x in range(n):
        yield x ** 2

In [93]:
list(gen_squares(10))

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [94]:
[x for x in gen_squares(10)]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [95]:
import random
def rand_num(low, high, n):
     for _ in range(n):
        yield random.randint(low, high)

In [96]:
[n for n in rand_num(20, 30, 10)]

[23, 26, 23, 28, 26, 26, 29, 24, 22, 30]

In [97]:
list(n for n in rand_num(20, 30, 10))

[22, 23, 21, 24, 25, 23, 27, 26, 23, 29]

In [98]:
for n in rand_num(20, 30, 10):
    print(n)

29
23
25
22
25
24
20
26
27
22


In [99]:
my_list = [1,2,3,4,5]

In [100]:
def my_filter(l):
    for item in filter(lambda x: x > 3, l):
        yield item

In [102]:
list(my_filter(my_list))

[4, 5]

In [104]:
list(iter([n for n in my_list if n > 3]))

[4, 5]

In [109]:
list(n for n in my_list if n > 3)

[4, 5]

In [112]:
ages_d = {'esmaili': 36, 'purbagher': 29, 'rabii': 'x', 'behruz': 32}

In [113]:
ages_d

{'esmaili': 36, 'purbagher': 29, 'rabii': 'x', 'behruz': 32}

In [115]:
[(k, v) for k, v in ages_d.items()]

[('esmaili', 36), ('purbagher', 29), ('rabii', 'x'), ('behruz', 32)]

In [117]:
new_d = dict([(k, v) for k, v in ages_d.items()])

In [118]:
new_d = {k: v for k, v in ages_d.items()}

In [119]:
new_d

{'esmaili': 36, 'purbagher': 29, 'rabii': 'x', 'behruz': 32}

In [120]:
new_d == ages_d

True

In [121]:
id(new_d)

2432602847976

In [122]:
id(ages_d)

2432603777448

In [124]:
{k: v-10 for k, v in ages_d.items() if type(v) == int}

{'esmaili': 26, 'purbagher': 19, 'behruz': 22}

### Sorted

In [125]:
import numpy as np

In [128]:
lst = np.array([random.randint(1, 100) for _ in range(15)])

In [129]:
lst

array([50, 37, 31, 36, 95, 44, 14, 17, 41, 93, 68,  6, 48, 71, 83])

In [130]:
sorted(lst)

[6, 14, 17, 31, 36, 37, 41, 44, 48, 50, 68, 71, 83, 93, 95]

In [131]:
lst

array([50, 37, 31, 36, 95, 44, 14, 17, 41, 93, 68,  6, 48, 71, 83])

In [133]:
sorted(lst, reverse=True)

[95, 93, 83, 71, 68, 50, 48, 44, 41, 37, 36, 31, 17, 14, 6]

In [134]:
class MyStringClass:
    def __init__(self, value):
        self.value = value
        
    def cost(self):
        v = 0
        for ch in self:
            v += ord(ch)
        return v
    
    def __iter__(self):
        return iter(self.value)
    
    def __repr__(self):
        return self.value

In [136]:
a = MyStringClass("Python")

In [137]:
a.cost()

642

In [138]:
a

Python

In [139]:
lst = [MyStringClass("Python"), MyStringClass("Course"), MyStringClass("101")]

In [140]:
lst

[Python, Course, 101]

In [141]:
for item in lst:
    print(item.cost())

642
625
146


In [142]:
sorted(lst, key=lambda item: item.cost())

[101, Course, Python]

In [144]:
my_int_lst = np.random.randint(-20, 20, 6)

In [145]:
my_int_lst

array([ 11,  -9, -18,  -4,   2,  -8])

In [149]:
sorted(my_int_lst, key=lambda item: item ** 2)

[2, -4, -8, -9, 11, -18]

In [150]:
sorted(my_int_lst)

[-18, -9, -8, -4, 2, 11]

# Decorators

In [151]:
# def func():
#     # Do simple stuff
#     return # something

In [152]:
# def func2():
#     # Do simple stuff
#     # Do something else
#     return # something

In [153]:
# # @some_decorator
# def func():
#     # Do simple stuff
#     return # something

In [154]:
def func():
    return 1

In [155]:
func()

1

In [156]:
func

<function __main__.func()>

In [157]:
def hello():
    return "hello!"

In [158]:
hello()

'hello!'

In [159]:
hello

<function __main__.hello()>

In [160]:
greet = hello()

In [161]:
greet

'hello!'

In [162]:
greet = hello

In [163]:
greet()

'hello!'

In [164]:
del hello

In [165]:
greet()

'hello!'

In [166]:
hello()

NameError: name 'hello' is not defined

# Passing a function into another function

In [167]:
def hello(name='world!'):
    print("The Hello() function has been executed!")

In [168]:
hello()

The Hello() function has been executed!


In [169]:
def hello(name='world!'):
    print("The Hello() function has been executed!")
    def greet():
        return "\t This is the greet() function inside hello()"

In [170]:
hello()

The Hello() function has been executed!


In [171]:
def hello(name='world!'):
    print("The Hello() function has been executed!")
    def greet():
        return "\t This is the greet() function inside hello()"
    print(greet())

In [172]:
hello()

The Hello() function has been executed!
	 This is the greet() function inside hello()


In [174]:
def hello(name='world!'):
    print("The Hello() function has been executed!")
    def greet():
        return "\t This is the greet() function inside hello()"
    
    def welcome():
        return "\t This is welcome() function inside hello!"
    print(greet())
    print(welcome())

In [175]:
hello()

The Hello() function has been executed!
	 This is the greet() function inside hello()
	 This is welcome() function inside hello!


In [176]:
welcome()

NameError: name 'welcome' is not defined

In [177]:
def hello(name='world!'):
    print("The Hello() function has been executed!")
    def greet():
        return "\t This is the greet() function inside hello()"
    
    def welcome():
        return "\t This is welcome() function inside hello!"
    
    
    if name == 'world!':
        return greet
    else:
        return welcome

In [178]:
my_new_func = hello()

The Hello() function has been executed!


In [179]:
my_new_func

<function __main__.hello.<locals>.greet()>

In [183]:
my_new_func = hello("donya")
print(my_new_func())

The Hello() function has been executed!
	 This is welcome() function inside hello!


In [181]:
print(my_new_func())

	 This is the greet() function inside hello()


In [184]:
def cool():
    def super_cool():
        return "I am very cool"
    return super_cool

In [185]:
some_func = cool()

In [186]:
some_func

<function __main__.cool.<locals>.super_cool()>

In [187]:
some_func()

'I am very cool'

In [188]:
def hello():
    return "hello world!"

In [190]:
def other(som_def_function):
    print("Other code runs here")
    print(som_def_function())

In [191]:
other(hello)

Other code runs here
hello world!


# Creating Decorators

In [193]:
def new_decorator(original_function):
    def wrap_func():
        print("Some extra code, before the original function")
        original_function()
        print('some extra code, after the original function')
    return wrap_func

In [194]:
def func_needs_decorator():
    print('I want to be decorated')

In [195]:
decprated_function = new_decorator(func_needs_decorator)

In [196]:
decprated_function()

Some extra code, before the original function
I want to be decorated
some extra code, after the original function


In [201]:
@new_decorator
def func_needs_decorator():
    print('I want to be decorated')

In [202]:
func_needs_decorator()

Some extra code, before the original function
I want to be decorated
some extra code, after the original function


In [203]:
class Dog:
    def __init__(self, name):
        self.name = name

In [204]:
dog = Dog("Rex")

In [205]:
hasattr(dog, 'name')

True

In [206]:
hasattr(dog, 'gender')

False

In [207]:
Dog.__name__

'Dog'

In [208]:
Dog.__dict__

mappingproxy({'__module__': '__main__',
              '__init__': <function __main__.Dog.__init__(self, name)>,
              '__dict__': <attribute '__dict__' of 'Dog' objects>,
              '__weakref__': <attribute '__weakref__' of 'Dog' objects>,
              '__doc__': None})

In [220]:
import inspect
def freeze_it(cls):
    def frozensetattr(self, key, value):
        if not hasattr(self, key) and inspect.stack()[1][3] != "__init__":
            print(f"Class {cls.__name__} is frozen. Can not set {key} = {value}")
        else:
            self.__dict__[key] = value
            
    cls.__setattr__ = frozensetattr
    return cls

In [221]:
@freeze_it
class A:
    def __init__(self):
        self.name = 0

In [222]:
a = A()

In [223]:
a.name

0

In [224]:
a.name = 'a'

In [225]:
a.name

'a'

In [226]:
a.b = 0

Class A is frozen. Can not set b = 0


In [ ]:
class A:
    
    def __setattr__(self, key, value)